#自定义参数
com:
  mall:
    admin:
      #每页显示的元素条数
      per-page-rows: 10
      #自定义静态资源路径，主要用来存放商品图片
      staticPath: D:\Codes\mall\static\

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: "huangkaiyan..QQ"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    # 在controller层就打开EntityManager，由controller层控制session的开启和关闭
    # 设置成false会导致懒加载报错
    open-in-view: true
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/static/,file:${com.mall.admin.staticPath}

server:
  servlet:
    session:
      #session 过期时间，单位：秒
      timeout: 180